/// Flutter icons PeAsIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PeAsIcons
///      fonts:
///       - asset: fonts/PeAsIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class PeAsIcons {
  PeAsIcons._();

  static const _kFontFam = 'PeAsIcons';
  static const _kFontPkg = null;

  static const IconData right = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xf0c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
